# Generated by Django 3.0 on 2020-09-16 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('season', models.CharField(blank=True, choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Either', 'Either')], max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
