# Generated by Django 3.0 on 2020-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200916_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
